# Generated by Django 6.0.3 on 2026-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
